---
title: "Race & Ethnicity: Household Counts"
output: 
  html_document:
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 19, fig.height = 9)

source(here::here("visuals/create-plots.R"))
```

# {.tabset}

## Region {.tabset}

### Count

```{r hhcount count}

hhc_re <- create_plots("household-count", 1, "count", "Region")

hhc_re_hhsize <- create_plots("household-count", 2, "count", "Region")

iwalk(hhc_re$plots, ~print(.x))

iwalk(hhc_re_hhsize$plots, ~print(.x))

```

### Shares

```{r hhcount share}

hhs_re <- create_plots("household-count", 1, "share", "Region")

hhs_re_hhsize <- create_plots("household-count", 2, "share", "Region")

iwalk(hhs_re$plots, ~print(.x))

iwalk(hhs_re_hhsize$plots, ~print(.x))

```

## King {.tabset}

### Count

```{r hhcount count king}

hhc_re_k <- create_plots("household-count", 1, "count", "King")

hhc_re_hhsize_k <- create_plots("household-count", 2, "count", "King")

iwalk(hhc_re_k$plots, ~print(.x))

iwalk(hhc_re_hhsize_k$plots, ~print(.x))

```

### Shares

```{r hhcount share king}

hhs_re_k <- create_plots("household-count", 1, "share", "King")

hhs_re_hhsize_k <- create_plots("household-count", 2, "share", "King")

iwalk(hhs_re_k$plots, ~print(.x))

iwalk(hhs_re_hhsize_k$plots, ~print(.x))

```

## Kitsap {.tabset}

### Count

```{r hhcount count kitsap}

hhc_re_kit <- create_plots("household-count", 1, "count", "Kitsap")

hhc_re_hhsize_kit <- create_plots("household-count", 2, "count", "Kitsap")

iwalk(hhc_re_kit$plots, ~print(.x))

iwalk(hhc_re_hhsize_kit$plots, ~print(.x))

```

### Shares

```{r hhcount share kitsap}

hhs_re_kit <- create_plots("household-count", 1, "share", "Kitsap")

hhs_re_hhsize_kit <- create_plots("household-count", 2, "share", "Kitsap")

iwalk(hhs_re_kit$plots, ~print(.x))

iwalk(hhs_re_hhsize_kit$plots, ~print(.x))

```

## Pierce {.tabset}

### Count

```{r hhcount count pierce}

hhc_re_p <- create_plots("household-count", 1, "count", "Pierce")

hhc_re_hhsize_p <- create_plots("household-count", 2, "count", "Pierce")

iwalk(hhc_re_p$plots, ~print(.x))

iwalk(hhc_re_hhsize_p$plots, ~print(.x))

```

### Shares

```{r hhcount share pierce}

hhs_re_p <- create_plots("household-count", 1, "share", "Pierce")

hhs_re_hhsize_p <- create_plots("household-count", 2, "share", "Pierce")

iwalk(hhs_re_p$plots, ~print(.x))

iwalk(hhs_re_hhsize_p$plots, ~print(.x))

```

## Snohomish {.tabset}

### Count

```{r hhcount count snohomish}

hhc_re_k <- create_plots("household-count", 1, "count", "Snohomish")

hhc_re_hhsize_k <- create_plots("household-count", 2, "count", "Snohomish")

iwalk(hhc_re_k$plots, ~print(.x))

iwalk(hhc_re_hhsize_k$plots, ~print(.x))

```

### Shares

```{r hhcount share snohomish}

hhs_re_s <- create_plots("household-count", 1, "share", "Snohomish")

hhs_re_hhsize_s <- create_plots("household-count", 2, "share", "Snohomish")

iwalk(hhs_re_s$plots, ~print(.x))

iwalk(hhs_re_hhsize_s$plots, ~print(.x))

```